sudo: false
language: python
python:
- 2.7
- 3.5
- 3.6

install:
- pip install pytest==3.8.2 pytest-cov codecov structlog wrapt pre-commit-hooks pytest-mock
script:
- pytest --cov=./
after_success:
- codecov
deploy:
  provider: pypi
  user: ksohit
  password:
    secure: d1bJRNOLLjbBeM9DfSFH13RyCy2wzxLFG/nDqnVYQOjoRglUV/OdmOAy0zUIXZWCaP7PWhA4EMl0q+OlxWic2DMjRcELoDj/ZYQAQvxE3ILwxZOjn4II8rEKv0bWshsPtCChkj1+vgEMTO+nNGdbElpYJDEvrhsIX3Gc5NwZn9tFeuvE3uqefCiszFZDxEycWijZmQ7LTN8KoxF2nOswElM5Bb92On3/73G8z8Q7TjYTXKPgVB3yU1dArih8KuEdRhI8rEB6rsAnIpIzsNd4Hc87GieAoPurpMdAEIv5qVBOwWCi8WMfCmvxBcLxaHR82iPP3zmM8bElnqosAJLsyouthQ6qnmzZ6CAFKJPZa8U2bakt8FhO7apPuRo7QTK2S1RfICHe0nszPOSbLA0NjdwOxDU5Y8L6+Fn+ejAPOcWf7ZSnWKJ7QKQ7HTxWxmh8nE2W3Kwi3SEnaJ00oUKWlgxOXIKRnax8ITQW7kCrcnd3mjxh0ktoyBQpf6QRXi1Nw4zW7XuR2J2XIhEwvpI0VAhjVl5+BFuBgsaCDyFMDTz9f30HDLLuB56dBig8IBCnIqBHf9D50vO3Ad75s6PyOrvl1VSjbuHGQ9J4G4ockhveTNmPe8xkROzqDxmeaXVbmdMuEnWFjymIoSP38lwxt/Wj22x2Dco+VBOuNO+kk/E=
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: '3.6'
