sudo: false

language: python

python:
- 3.6

install:
- pip install pytest pytest-cov codecov structlog wrapt pre-commit-hooks black pytest-mock

script:
- pytest --cov=./

after_success:
- codecov

deploy:
  provider: pypi
  user: ksohit
  password:
    secure: avBlLJqlKl2yOuRtZ01x57I+iQ2jLEnkR2IG/1LeQvP930EkjAhBwAYvfe2kc9xxL126+wV7UPLwI2jB0Jq3BJC2wkFEpkH6fJFrqtNldEclxCMlPWRrglKYe5co7QuevVnJJgpPIwvh1LV63/YNNot+9OycOPaVwBaH3T7z1EZxmggcT5o/vrdRJkLsO2sLKZWjW3T6xlcushcxk1Ae1MYAsElyc108/rnjCnLHx3aBUIcGb6rIq2h4d9RZJNUJ83oEbkn60GFFc8zAuBZ52bgIjjdAKSeCuf1i4gqkli9EmJK/q7wuV9Gx3YxizR86d2xcjHa0os73OBqS7wHH4u3/Z4xXJlMND/AdHUT2YPL4SY6qgiBmHYlCURZi6FoSV3t1wZobHdzwo0mHoqY/Q4xNlHYx8Fg7eyi8UvVPZSeYmt4b9ooPB+HKXLz/6dTsgNaf6o8KtsW3q7wPmzLGLgfatftLqjsijjAcCmA2Fl0HeVRSXVEVVTyG4i1MSE2onbFNoGVEQQWnIji2xc0dm2ji2hxc6YuwpDI0jnFHWFvXXymvmlFoNko83FsI3ZlqdTWG/RDp5uv+JrioaVPdlczzjtwex1/sIMXbEkPMgzweQ8QgJFkG7WNk4H/kJl9j3qWrMjSvqXjvpYJhGNlDgkPm3RgwoBYt+E1LSTfI3N0=
  distributions: "sdist bdist_wheel"
